
application:
  name: "helm-chart-chatbot"
  namespace: "ai-software-templates-dev"
  appPort: 8501
  appContainer: "quay.io/redhat-ai-dev/chatbot:latest"

model:
  initContainer: "quay.io/redhat-ai-dev/granite-7b-lab:latest"
  modelInitCommand: "['/usr/bin/install', '/model/model.file', '/shared/']"
  modelPath: "/model/model.file"
  modelServiceContainer: "quay.io/ai-lab/llamacpp_python:latest"
  modelServicePort: 8001

gitops:
  gitSecretName: "github-secrets"
  gitSecretKeyToken: "GITHUB_TOKEN"
  gitSourceRepo: "redhat-ai-dev/ai-lab-samples"
  gitDefaultBranch: "main"
  githubOrgName: ""
  quayAccountName: ""