name: Release Helm Chart Package

on:
  push:
    tags:
      - "v*"
permissions:
  contents: write

jobs:
  release-package:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        chartpath:
          - "charts/chatbot"
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Install Helm
        uses: azure/setup-helm@fe7b79cd5ee1e45176fcad797de68ecaf3ca4814 # v4.2.0
        with:
          version: 3.12.1

      - name: Generate Helm Package
        run: |
          RELEASE_VERSION=${GITHUB_REF#refs/*/}
          CHART_PATH=${{matrix.chartpath}}
          helm package $CHART_PATH/$RELEASE_VERSION
