apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: {{ .Values.application.name }}
    app.kubernetes.io/name: {{ .Values.application.name }}
  name: {{ .Values.application.name }}
  namespace: {{ .Values.application.namespace }}
spec:
  ports:
  - port: {{ .Values.application.appPort }}
    protocol: TCP
    targetPort: {{ .Values.application.appPort }}
  selector:
    app.kubernetes.io/instance: {{ .Values.application.name }} 
