apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.application.name }}-model-config
  namespace: {{ .Values.application.namespace }}
data:
  MODEL_ENDPOINT: "http://{{ .Values.application.name }}-model-server:{{ .Values.model.modelServicePort }}"